"""Verbatim EXS24 block templates lifted from a known-good factory kit.

Source: Logic's own "Pure House Kit" (03 Drums & Percussion / 02 Electronic
Drum Kits) — a modern little-endian ("TBOS") EXS with a clean 1:1 zone↔sample
layout (17 mono-mappable one-shots, one WAV each), the same shape our exporter
produces. We patch per-instance fields (root key, ranges, sample/group indices,
lengths, file names) into these and reuse the structural blocks as-is.

Why templates instead of hand-rolling every byte (as the old big-endian writer
did): the modern format carries fields Logic actually reads that the old writer
left zero — most importantly the PARAMS block's global voice count (16) at
offset 112. An all-zero params block reads as 0 voices, so every new note steals
the one voice → the "drums cut each other off" gating the user reported. Copying
the factory PARAMS verbatim fixes that for free.

Field offsets (little-endian) used by logic_export.py:
  INSTR (88B):  @4 n_zones, @8 n_groups, @12 n_samples, @16 n_params,
                @28 n_t7, @32 n_t8, @40 bplist-present flag
  ZONE (148B):  @0 opts, @1 root key, @6 key low, @7 key high, @9 vel low,
                @10 vel high, @16 & @24 sample end (frames), @88 group index,
                @92 sample index, @112 = -1 (constant)
  GROUP (140B): @2 polyphony (0=max), @3 options (bit0=polyphonic). Used
                verbatim — one group per key. (@80 and @90 are a group-chain
                mechanism the writer deliberately does NOT use: in the modern
                format they create voice-stealing, not round-robin. Round-robin
                comes from overlapping same-key zones, which Logic auto-cycles.)
  SAMPLE(600B): @0 data offset, @4 frames, @8 sample rate, @12 bit depth,
                @16 channels, @20 channels2, @28 type 4cc (byte-reversed),
                @32 file size, @80 abs dir path (asciiz), @336 file name (asciiz)
  PARAMS(1108B):@112 global voices (16) — the anti-gating field. Used as-is.
"""

from __future__ import annotations

import base64

INSTR_TMPL = base64.b64decode(
    "AAAAABEAAAAGAAAAEQAAAAEAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)

ZONE_TMPL = base64.b64decode(
    "AzYAAPUANjYAAH8AAAAAAMBdAAAAAAAAwF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAQAgE8SAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAP//"
    "//8AAAAAAAAAAAAAMMEAAAAAAAAAAAAAAAAAAAB+WIp9YA=="
)

GROUP_TMPL = base64.b64decode(
    "AAAAAQAAfwD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQGAAABQjAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAEAAAAAAD/////AAAAAAB/AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAABAAAfv+1eWA="
)

SAMPLE_TMPL = base64.b64decode(
    "ABAAACJWAABErAAAGAAAAAIAAAACAAAAAQAAAEZGSUH4GAIAAAAAAAAAAAAQAAAAAAAAAAAAAAAA"
    "APhCAAAAAAAAAAAAAAAAAAAAAAAAAAAvTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0xvZ2lj"
    "L0VYUyBGYWN0b3J5IFNhbXBsZXMvMDMgRHJ1bXMgJiBQZXJjdXNzaW9uLzAyIEVsZWN0cm9uaWMg"
    "RHJ1bSBLaXRzL1B1cmUgSG91c2UgS2l0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ2xhcCAx"
    "IC0gUHVyZSBIb3VzZS5haWYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO4hJ6Jg"
)

PARAMS_TMPL = base64.b64decode(
    "ZAAAAAcIAwQFFEnzHh1LLlpZPD0+QD9MTU5PUFxSU1RRVWGlp6asra6vsLGztLW2t/4AAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD//xAA"
    "AAAAAAAA6AMAAGQAAADE/wAAAABiAAAAAABiAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAEAYgD/"
    "/0AACADy////AAAAAAYA9P8BAAAAVwHoAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAMgAAAB6AQAAdwHoA3gBAAB5AWQAhQEDAIYBAwBrAQIA9AEAAGoB"
    "AgD1AQAAYQECAGIBAABjAQAAZQEAAGYBAABnAQAA9gEAAPcBAgD5AQAA+gEAAP0BAAD/AQAAAAIA"
    "AAMCAAAEAgIABgIAAAcCAAAKAgAADAIAAA0CAAAQAgAATwEAAE4BAABQAQAAUQEAAFUBAABUAQAA"
    "VgEAAFcBAABYAQAAWwEAAF0BAADsAQAA6wFiAO0BAADwAQAA8gEAABcCAQAaATAAgwH2/4QBAQAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)

# The six factory "output" blocks (type 8). Content is 4 zero bytes each; the
# names are cosmetic bus labels. Every sampled factory kit ships exactly these.
T8_NAMES = ["Kick", "Snare/Clap", "Hi-Hat", "Toms", "Percussion", "Cymbal/FX"]
T8_CONTENT = b"\x00\x00\x00\x00"


# --- Round-robin ('classic' EXS24) format, from Logic's 'Electronic Snare D1 6' ---
# Older/simpler EXS variant that DOES round-robin multiple full-velocity zones
# sharing a group (the modern 148-byte format never does). Separate WAVs, LE.
# Block header uses a PLAIN type byte (no 0x40). No output/bplist blocks.
# INSTR_RR_TMPL len=40
INSTR_RR_TMPL = base64.b64decode(
    "AAAAAAIAAAABAAAAAgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)
# ZONE_RR_TMPL len=108
ZONE_RR_TMPL = base64.b64decode(
    "ACYAAPcAAH8AAH8AAAAAABtqAAAAAAAAG2oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgE8SAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
)
# GROUP_RR_TMPL len=120
GROUP_RR_TMPL = base64.b64decode(
    "ANkBAQAAfwD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAgAwAAAAAAAAAAAAD/////AAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAA"
)
# SAMPLE_RR_TMPL len=592
SAMPLE_RR_TMPL = base64.b64decode(
    "AAIAABtqAABErAAAEAAAAAIAAAACAAAAAQAAAEZGSUFsqgEAAAAAAAAAAAAQAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAnP///x8hCgAvTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0xvZ2lj"
    "L0VYUyBGYWN0b3J5IFNhbXBsZXMvMDMgRHJ1bXMgJiBQZXJjdXNzaW9uLzAzIFNpbmdsZSBEcnVt"
    "cy8wMiBTbmFyZXMvRWxlY3Ryb25pYyBTbmFyZXMvRWxlY3Ryb25pYyBTbmFyZSBEMSA2AAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARFIgODA4"
    "c25nYXRlLmFpZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)
# PARAMS_RR_TMPL len=304
PARAMS_RR_TMPL = base64.b64decode(
    "ZAAAAAcIAwQFFEhJLPOqHh1LLlpZPD0+QD9MTU5PUFxbUlNUUVVfYmGlp6asra6vsLGztLW2t7i5"
    "uru8vb/AwcLDxcbHyMnLzM3Oz9HS09TV19jZ2tvd3t/g4ePk5ebnAAAAAAAAAAAAAAAADAAkABAA"
    "AAAAAAAAAQAAAAEAAAAAAGQAAADo/wAAAAAiAAAAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwAs"
    "AAAAAAAAAAEAIgD//0AAAgD9////6APoAwgA8P8BAAAA6AMBAAkA8P8BAAAAVwIAAP////8AAAAA"
    "AAD/////AAAAAAAA/////wAAAAAAAP////8AAAAAAAD/////AAAAAAAA/////wAAAAAAAP////8A"
    "AAAAAAAAAAAAAAAAAAAAAAAAAA=="
)
