"""Verbatim EXS24 block templates, lifted from the user's Logic-authored
reference instrument.

Source: "Round Robin / Gated Hat Reference.exs" — built BY HAND in Logic's
Sampler UI (round-robin kicks/snares + exclusive-class-1 gated hats, using this
app's own exported WAVs) and VERIFIED BY EAR in Logic before being adopted
here. That makes these templates ground truth: the writer patches per-instance
fields (keys, ranges, indices, lengths, file names, RR chain/select, choke
class) and reuses every other byte exactly as Logic saved it.

Why templates instead of hand-rolling every byte: the modern format carries
fields Logic actually reads that a from-scratch writer would leave zero (e.g.
the PARAMS voice count, the group "select by" mode). Cloning the verified file
sidesteps a whole class of silent-field bugs that plagued earlier attempts.

Field offsets (little-endian) used by logic_export.py:
  INSTR (88B):  @4 n_zones, @8 n_groups, @12 n_samples, @16 n_params,
                @28 n_t7, @32 n_t8, @40 bplist-present flag
  ZONE (148B):  @0 opts, @1 root key, @6 key low, @7 key high, @9 vel low,
                @10 vel high, @16 & @24 sample end (frames), @88 group index,
                @92 sample index, @112 = -1 (constant)
  GROUP (140B): @2 voices (0=max, 1=mono), @3 options (bit0=polyphonic),
                @4 exclusive/choke class (hats use 1), @80 round-robin
                previous-group chain (head -1, each later group → the prior
                one), @84 group "select by" mode (2 = round robin — REQUIRED
                for the @80 chain to rotate; without it the chain chokes),
                @90 must stay 0. Semantics confirmed against the user's
                Logic-authored "Round Robin / Gated Hat Reference" instrument.
  SAMPLE(600B): @0 data offset, @4 frames, @8 sample rate, @12 bit depth,
                @16 channels, @20 channels2, @28 type 4cc (byte-reversed),
                @32 file size, @80 abs dir path (asciiz), @336 file name (asciiz)
  PARAMS(1108B):@112 global voices (16) — the anti-gating field. Used as-is.
"""

from __future__ import annotations

import base64

INSTR_TMPL = base64.b64decode(
    "AAAAAAcAAAAHAAAABwAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)

ZONE_TMPL = base64.b64decode(
    "CSQAAAAAJCQAAH8AAAAAAC4qAQAAAAAALioBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAgE8SAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAP//"
    "//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAB79TRkag=="
)

GROUP_TMPL = base64.b64decode(
    "AAAAAQAAfwD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQGAAABQjAAAAAAAAAAAAAAAAAQAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AgAAAAB/AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAARQAAe/U0ZGo="
)

SAMPLE_TMPL = base64.b64decode(
    "LAAAAACOAQBErAAAGAAAAAEAAAABAAAAAAAAAEVWQVegrgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "APBCAAAAAAAAAAAAAAAAAAAAAAAAAAAvVXNlcnMvd2lsbGlhbWxvbm9uL011c2ljL0F1ZGlvIE11"
    "c2ljIEFwcHMvU2FtcGxlciBJbnN0cnVtZW50cy9TYW1wbGVib3QtMzAwMAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARGFkcyBP"
    "bGQgS2l0IC0gQ18yLndhdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAIMAAHv2NGRq"
)

PARAMS_TMPL = base64.b64decode(
    "ZAAAAAcIAwQFFEnzHh1LLlpZPD0+QD9MTU5PUFxSU1RRVWGlp6asra6vsLGztLW2t/4AAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAgD//xAA"
    "AAAAAAAA1gGPAtoBAADE/wAAAABiAAAAAABiAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAEAYgD/"
    "/0AACADy////AAAAAAYA9P8BAAAAVwHoAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAMgAAAB6Aev/dwHoA3gBAAB5AWQAhQEDAIYBAwBgAToAawECAPQB"
    "AABqAQIA9QEAAGEBAgBiAQAAYwEAAGUBAABmAQAAZwEAAPYBAAD3AQIA+QEAAPoBAAD9AQAA/wEA"
    "AAACAAADAgAABAICAAYCAAAHAgAACgIAAAwCAAANAgAAEAIAAE8BAABOAQAAUAEAAFEBAABVAQAA"
    "VAEAAFYBAABXAQAAWAEAAFsBAABdAQAA7AEAAOsBYgDtAQAA8AEAAPIBAAAXAgEAGgEwAIMB9v+E"
    "AQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)

# Unused: the six factory "output" bus-label blocks (type 8). The reference
# instrument omits them, so the writer does too; kept for format documentation.
T8_NAMES = ["Kick", "Snare/Clap", "Hi-Hat", "Toms", "Percussion", "Cymbal/FX"]
T8_CONTENT = b"\x00\x00\x00\x00"

